spring:
  application:
    name: DistributedJobSchedule
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
